
title: Autopflege Mieth
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://autopflege-mieth.de" # the base hostname & protocol for your site
exclude:
  - node_modules/
  - Gulpfile.js
  - src/
  - package.json
  - README.md
include:
  - dist/

# Build settings
markdown: kramdown

# Descriptions
stufe1_desc: "Ideal für gut gepflegte Fahrzeuge und wenn dein Lack nur leichte Hologramme und Swirls hat!"
stufe2_desc: "Standard-Paket für gehobene Ansprüche und wenn dein Lack viele und tiefe Kratzer hat!"
stufe3_desc: "Dein Oldtimer wird auf einer Messe ausgestellt oder du möchtest ein Wertgutachten erstellen? Stufe 3 holt das maximum raus."
serum_desc: "Die absolute Ausnahmeversiegelung! Beispiel gefällig? <a href='https://glossboss.de/produkttest/gtechniq-crystal-serum-test-anwendung-auftrag/' target='_blank'>Crystal Serum Produkttest auf glossboss.de</a> <p>Für den Auftrag ist einer der 3 Stufen erforderlich.</p>"
exo_desc: "Als Topping zum Gtechniq Crystal Serum, zaubert das Exo wunderschöne Wasserperlen auf den Lack!"
seminar_desc: "Verbessere deine Poliertechnik im Einzelseminar oder lerne die Grundlagen der Fahrzeugpflege in einer Gruppenschulung - individuelle Schulungen perfekt auf dich oder deine Gruppe abgestimmt."
